package-lock.json
package.json

Since the update of mantine 7, there's no need for emotion... let's drop this

chore(deps): remove uncessary emotion

---

src/App.tsx

it seems there's a settings, but when the browser loads, it doesn't restore the prefered lang :) 
here is an attempt fix

fix: restore save lang on load

---

biome.json
firebase.json
package-lock.json
package.json
public/service-worker.js
src/App.test.tsx
src/components/editcard/CardEditor/ClozeCardEditor.tsx
src/components/settings/Section.tsx
src/logic/card.tsx
src/logic/card_filter.ts
src/logic/db.ts
src/logic/deck.ts
src/logic/frame.ts
src/logic/learn.ts
src/logic/sharedvalue.ts
src/reportWebVitals.ts
src/setupTests.ts

Hey 👋 
Me again, 
sorry if this is controversial... hopefully not :) 
Often when contributing to a projet, you'll have to adapt to [new] norm of coding.
For this having a Linter, but above all, a formatter is important to convey the standard.
I looked at prettier, but it seems it was unmaintained, and not run since a few errors are poppings.
As such, i though of using biome, IMHO, it's probably the next prettier, already acheiving 97% of compatibilty ... and it comes bundled with a linter... 
I fixed the code to match the formatter and a few lint... but maybe we might want to go a bit further, with CI & stuff ...
Anyways, let me know what you think about it ... i can go to a more conventional prettier & ESLint if needed.
Note: i split the config, the format & auto lint fix for readability

Format & Lint using Biome 

---

src/App.tsx

fix: correct notif after mantine update

---

src/App.tsx

just merged, and already broken 😅 ...
Sorry it was the other PR, I didn't check... 
anyway, here is the tiny fix

fix(lint): correct quote style

---

i18next-parser.config.mjs
package-lock.json
package.json
src/components/deck/DeckPreview.tsx
src/i18n/locales/de/translation.json
src/i18n/locales/en/translation.json
src/i18n/locales/sv/translation.json

Hello,
again some tooling improvement here :)  hope you don't mind :p 
want to do UI improvement too , but don't really want to disrupt your plans... 
anyways, not sure how you did it until now, but here i a way to automate the i18n extraction...
that way it will be easier to translate all the things...
i've add a new commit to manage some plurals too … even if we don't want to display it differently at the moment.
As always, let me know if you have questions, objections, remarks :)

Translation Extraction

---

src/components/DebugCardModal/DebugCardModal.tsx
src/logic/CardTypeImplementations/ClozeCard.tsx

- fix: right handside ?? is useless
- fix: correct missing key in loop to avoid errors

Small Fixes

---

src/components/HomeView.tsx
src/i18n/locales/de/translation.json
src/i18n/locales/en/translation.json
src/i18n/locales/sv/translation.json

small fix
you were correct, it seems I let this slipped, 
in fact to be extracted the string must be like t('...') thus doing computation there won't work... 
here is a fix :)

fix: correct translation to be extractable

---

biome.json
src/components/custom/Stat/Stat.tsx
src/components/editcard/CardEditor/ClozeCardEditor.tsx
src/components/editcard/CardEditor/DoubleSidedCardEditor.tsx
src/components/editcard/CardEditor/NormalCardEditor.tsx
src/components/editcard/CardMenu.tsx
src/components/settings/ColorSchemeToggle.tsx
src/components/settings/importexport/ImportButton.tsx
src/components/settings/importexport/ImportFromJSON.tsx
src/logic/CardTypeImplementations/UndefinedCard.tsx
src/logic/deck.ts

sorry, 
the ci failed, but had no time to fix it... 
here it is now , with some unused variable as detected by biome

chore: missng fix from remove import

---

src/components/deck/SubDeckSection.tsx
src/components/notebook/NotebookView.tsx
src/components/settings/SettingsView.tsx
src/i18n/locales/de/translation.json
src/i18n/locales/en/translation.json
src/i18n/locales/sv/translation.json

there are plenty of translations missing, 
not sure if we need to hunt them down or waiting for things to settle a bit?

chore: add some missing translations

---

src/components/sidebar/DeckTree.tsx
src/components/sidebar/Sidebar.tsx

decide to not display it in mobile.... 
it probably need polish, what do you think about it, the elements, the buttons, ....
?

feat: add tree deck list in sidebar

---

src/components/sidebar/Sidebar.tsx

using close icon, fixing tooltips, and reworking organisation
Also fix for deck list display in minimal mode

feat: improve sidebar display

---

src/components/CardManagerView/CardManagerView.tsx
src/components/CardTable/CardTable.tsx
src/components/CardTable/CardTableHeadItem.tsx
src/logic/card_filter.ts

narrow down the possible sort field

chore: type sort field

---

.vscode/settings.json
i18next-parser.config.mjs
src/components/editcard/CardEditor/CardEditor.tsx
src/components/editcard/CardEditor/ClozeCardEditor.tsx
src/components/editcard/CardEditor/DoubleSidedCardEditor.tsx
src/i18n/locales/de/translation.json
src/i18n/locales/en/translation.json
src/i18n/locales/sv/translation.json

seems you did the Normal editor only, 
so i copied the logic in other cards

Add submit editor

---

src/components/notebook/NotebookCard.tsx
src/components/sidebar/Sidebar.tsx
src/i18n/locales/de/translation.json
src/i18n/locales/en/translation.json
src/i18n/locales/sv/translation.json

small improvement here 
- translation
- heavy flickering while dragging a card 😅

chore: small improvement in dnd

---

src/components/notebook/NotebookView.tsx
src/i18n/locales/de/translation.json
src/i18n/locales/en/translation.json

As it seems the menu.item and toggle conflicted...  and it was hard to toggle
this should correct it.

Fix Notebook options

---

src/logic/Settings.ts
src/logic/ui.ts

fix #69
You can't really call a hook conditionally ...

fix: correct hook issues

---

src/components/settings/LanguageSelect.tsx
src/logic/Settings.ts

seems that ES isn't supported yet

chore: add enum for lang and avoid extra keys

---

package-lock.json
package.json

boring stuff... 
maybe new icons might be interesting :)

chore(deps): upgrade some deps especially icons

---

biome.json
package.json
src/components/deck/DeckView.tsx
src/components/learning/LearnViewCurrentCardStateIndicator/LearnViewCurrentCardStateIndicator.tsx

because it might break some of the things 😅

fix: correct conditional hooks and enable lint

---

src/components/editcard/CardEditor/ClozeCardEditor.tsx
src/components/editcard/CardEditor/DoubleSidedCardEditor.tsx
src/components/editcard/CardEditor/NormalCardEditor.tsx
src/components/editcard/EditNoteModal.tsx
src/components/editcard/NoteMenu.tsx
src/logic/CardTypeImplementations/ClozeCard.tsx
src/logic/CardTypeImplementations/DoubleSidedCard.tsx
src/logic/CardTypeImplementations/NormalCard.tsx
src/logic/TypeManager.tsx

Hey, 
small improvement, it seems to work well but not sure of the implications 🤔 
I just noticed the shortcut is now a bit more broken than before in notebookview,
but they probably need a rework anyway there 😅

feat: add edit modal

---

.github/workflows/check.yml
biome.json
package-lock.json
package.json
src/components/editcard/CardEditor/ClozeCardEditor.tsx
src/components/settings/DatabaseSettingsView/StorageSection.tsx
src/logic/learn.ts

Biome Upgrade

---

package-lock.json
package.json
src/App.test.tsx
src/setupTests.ts

I'm unsure about webvitals #99  .. seems not "really" used... but maybe you have a plan ...
also, i removed them not because i hate them, but just because they are useless as of now... we can bring them back if needed

chore(deps): remove unused deps

---

package-lock.json

because of https://github.com/vitejs/vite/issues/15120

chore(deps): attempt to regen the lock file

---

src/components/CardTable/NoteTableItem.tsx
src/components/editcard/EditCardView.tsx
src/components/editcard/NewCardsView.tsx
src/i18n/locales/en/translation.json
src/logic/card.ts

long time no see :) 
here is a quick translation PR

chore: add translations for card types

---

.github/workflows/check.yml
.vscode/extensions.json
.vscode/settings.json
package-lock.json
package.json
src/components/settings/LearnSettingsView.tsx

chore: improve dev experience with extensions reco + easy lint fix

---

.github/workflows/check.yml
biome.json
package-lock.json
package.json
src/components/editcard/CardEditor/NoteEditor.tsx

fix: correct biome checks
